In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\LINGESH A\OneDrive\Desktop\py\top_creators_impact_2025.csv")
df

,author_handle,platform,n_videos,views,avg_er,likes_sum,dislikes_sum,comments_sum,shares_sum,saves_sum,total_engagements,avg_engagement_velocity,avg_comment_ratio,avg_share_rate,avg_save_rate,avg_like_dislike_ratio,avg_engagement_per_1k,avg_like_rate,avg_dislike_rate,creator_avg_views
0,UrbanVision,TikTok,136,17938952,0.091914,1267238,36094,142403,125916,124572,1660129,17957.902500,0.007648,0.006849,0.007302,49.735210,91.913699,0.070115,0.001887,120866.4
1,BeyondStudio,TikTok,135,17085072,0.087916,1121223,31594,123017,114620,130934,1489794,17890.303481,0.007439,0.006496,0.006724,49.875449,87.915533,0.067256,0.001922,116192.9
2,StreetVision,TikTok,133,16843324,0.093018,1228515,28953,129169,114222,138762,1610668,18574.954962,0.007454,0.006886,0.007555,54.076138,93.018098,0.071123,0.001870,116083.5
3,NextMedia,TikTok,148,16325236,0.092222,1161803,29124,128881,110655,119691,1521030,15570.731419,0.007605,0.006733,0.007361,53.285924,92.222081,0.070523,0.001818,106288.7
4,PrimeLabs,TikTok,135,16240032,0.092307,1095828,28067,119613,105152,112859,1433452,15412.244000,0.007698,0.006751,0.007717,52.907430,92.306830,0.070140,0.001816,103134.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,GuruYuki,YouTube,21,1865526,0.050216,80938,8694,9343,8018,7906,106205,9052.485714,0.004140,0.003819,0.004129,14.826263,50.215571,0.038128,0.003620,86547.9
996,OfficialSofia,TikTok,18,1858897,0.090631,126563,2813,13248,11468,15048,166327,9671.951111,0.008100,0.006263,0.006582,54.694049,90.631278,0.069687,0.001562,102487.9
997,TravelByNoor,YouTube,18,1857824,0.056072,69365,6231,7680,6363,5358,88766,12190.825556,0.004760,0.004138,0.003585,13.591240,56.071944,0.043590,0.004124,96440.7
998,TVDiego,YouTube,20,1856301,0.055188,71928,6373,8041,7128,8984,96081,13751.414500,0.004523,0.004063,0.004867,13.170205,55.187650,0.041735,0.003821,108068.4
999,BeautyByAmr,TikTok,21,1854548,0.092891,117331,2368,10812,10748,9943,148834,16431.634286,0.007505,0.006813,0.006816,49.267076,92.890762,0.071757,0.001755,90734.5

In [2]:
df.shape

(1000, 20)

In [5]:
tt_top=df.sort_values(by="views",ascending=False)
tt_top.loc[tt_top["platform"]=="TikTok",["author_handle","views"]].head(10)

  author_handle     views
0   UrbanVision  17938952
1  BeyondStudio  17085072
2  StreetVision  16843324
3     NextMedia  16325236
4     PrimeLabs  16240032
5    NextVision  15358183
6     BeyondHub  14998702
7     VividLabs  14825789
8    VividWorks  14056602
9  InsideVision  13895416

#### This shows top 10 creators in TikTok with most views

In [6]:
tt_top.loc[tt_top["platform"]=="YouTube",["author_handle","views"]].head(10)

   author_handle     views
19    VividWorks  13100235
21    PrimeMedia  12796075
43     VividLabs  10197573
44   BeyondWorks  10050064
47    NextStudio   9790132
49       NextHub   9762487
52  BeyondStudio   9635708
53  StreetStudio   9609984
54     BeyondHub   9549059
57     UrbanLabs   9454222

#### This shows top 10 creators in YouTube(only shorts) with most views